CREATE DATABASE IF NOT EXISTS taller CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;
USE taller;

CREATE TABLE operadores (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    pin CHAR(4) NOT NULL,
    coste_hora DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    tiempo_operativo INT NOT NULL DEFAULT 480,
    activo TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pin (pin)
) ENGINE=InnoDB;

CREATE TABLE clientes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL DEFAULT '',
    telefono VARCHAR(20) NOT NULL DEFAULT '',
    email VARCHAR(150) NOT NULL DEFAULT '',
    direccion VARCHAR(255) NOT NULL DEFAULT '',
    notas TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE vehiculos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT UNSIGNED NOT NULL,
    marca VARCHAR(80) NOT NULL DEFAULT '',
    modelo VARCHAR(80) NOT NULL DEFAULT '',
    matricula VARCHAR(20) NOT NULL DEFAULT '',
    bastidor VARCHAR(50) NOT NULL DEFAULT '',
    anio VARCHAR(4) NOT NULL DEFAULT '',
    color VARCHAR(40) NOT NULL DEFAULT '',
    vin VARCHAR(50) NOT NULL DEFAULT '',
    notas TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE partes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cliente_nombre VARCHAR(150) NOT NULL,
    cliente_apellidos VARCHAR(150) NOT NULL DEFAULT '',
    vehiculo_marca VARCHAR(80) NOT NULL DEFAULT '',
    vehiculo_modelo VARCHAR(80) NOT NULL DEFAULT '',
    matricula VARCHAR(20) NOT NULL DEFAULT '',
    bastidor VARCHAR(50) NOT NULL DEFAULT '',
    telefono VARCHAR(20) NOT NULL DEFAULT '',
    cliente_id INT UNSIGNED DEFAULT NULL,
    vehiculo_id INT UNSIGNED DEFAULT NULL,
    operador_id INT UNSIGNED DEFAULT NULL,
    estado ENUM('abierto','cerrado') NOT NULL DEFAULT 'abierto',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (operador_id) REFERENCES operadores(id) ON DELETE SET NULL,
    FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL,
    FOREIGN KEY (vehiculo_id) REFERENCES vehiculos(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE tareas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parte_id INT UNSIGNED NOT NULL,
    descripcion TEXT NOT NULL,
    tiempo_estimado DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    tiempo_real DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    observaciones TEXT,
    cerrada TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parte_id) REFERENCES partes(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE registros_tiempo (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tarea_id INT UNSIGNED NOT NULL,
    operador_id INT UNSIGNED NOT NULL,
    minutos DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    nota VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tarea_id) REFERENCES tareas(id) ON DELETE CASCADE,
    FOREIGN KEY (operador_id) REFERENCES operadores(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE articulos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parte_id INT UNSIGNED NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    precio_coste DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    precio_venta DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    cantidad DECIMAL(8,2) NOT NULL DEFAULT 1.00,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parte_id) REFERENCES partes(id) ON DELETE CASCADE
) ENGINE=InnoDB;
